### PR TITLE
Boot using all 8 Cores

### PR DESCRIPTION
**Pull request by netship69**
Faster Bootup.  ^_^

### CODE REVIEW

**Comment by netship69** [comment]
@danielstuart14

**Comment by danielstuart14** [comment]
you'd add this for msm8929 & msm8939_v3

**Comment by netship69** [comment]
Ohk.. but msm8929 has this
#include "msm8939.dtsi"
So , i guess i only need to edit msm8939_v3.dtsi

**Comment by danielstuart14** [comment]
Thx! Just one more thing, hehe.
I rebased the kernel. Can you do the PR again? :p 

The lineout hack wasn't working as supposed to

**Pull request merged**
